language: go

go:
  - '1.12'

script:
  - export GO111MODULE=on CGO_ENABLED=1
  - go get
  - mkdir -p $HOME/.config/kustomize && ln -s $PWD/plugin $HOME/.config/kustomize/
  - cd plugin/sourceability.com/v1/kep897patch/
  - GOROOT=$(go env GOROOT) go test -v Kep897Patch_test.go
