language: go

go:
  - '1.12'

script:
  - export GO111MODULE=on CGO_ENABLED=1 GOROOT=$(go env GOROOT)
  - mkdir -p $HOME/.config/kustomize && ln -s $PWD/plugin $HOME/.config/kustomize/
  - go test -v plugin/sourceability.com/v1/kep897patch/Kep897Patch_test.go
