apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels: &labels
    app: elasticsearch
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch