apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: &labels
    app: nginx
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: nginx
          image: nginx